const APP_CONFIG = {
    backendHost: process.env.NEXT_PUBLIC_SS_BACKEND_HOST,
        NEXTAUTH_SECRET:process.env.NEXT_PUBLIC_NEXTAUTH_SECRET,
        NEXTAUTH_URL:process.env.NEXT_PUBLIC_NEXTAUTH_URL,

        GOOGLE_CLIENT_ID:process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET:process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,

        REDIRECT_URL_SUCCESS:process.env.NEXT_PUBLIC_REDIRECT_URL_SUCCESS,
        BACKEND_URL:process.env.NEXT_PUBLIC_BACKEND_URL,
  };
  
  export default APP_CONFIG;
  