import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SuperShop",
  description: "Generated by Prateek Dixit",
  icons : {
    icon: ['/favicon.ico?v=4'],
    apple: ['/apple-touch-icon.ico?v=4'],
    shortcut: ['/apple-touch-icon.ico']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
